import { SignInButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!!user.isSignedIn && (
            <div className="text-white">
              <h1 className="text-4xl font-bold">
                Hello {user?.user?.emailAddresses?.[0]?.emailAddress}!
              </h1>
              <p className="text-2xl">You are signed in.</p>
            </div>
          )}
          {!user.isSignedIn && (
            <div className="text-white">
              <h1 className="text-4xl font-bold">Hello!</h1>
              <p className="text-2xl">You are not signed in.</p>
              <SignInButton />
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
